#!/system/bin/sh

MODDIR=${0%/*}
PATCHED_XML=$MODDIR/floating_feature.xml.patched
ORIGINAL_XML=/system/etc/floating_feature.xml

sed '/<SEC_FLOATING_FEATURE_COMMON_CONFIG_DEX_MODE>/s/, *standalone//; /<SEC_FLOATING_FEATURE_COMMON_CONFIG_DEX_MODE>/s/<SEC_FLOATING_FEATURE_COMMON_CONFIG_DEX_MODE>\(.*\)<\/SEC_FLOATING_FEATURE_COMMON_CONFIG_DEX_MODE>/<SEC_FLOATING_FEATURE_COMMON_CONFIG_DEX_MODE>\1,standalone<\/SEC_FLOATING_FEATURE_COMMON_CONFIG_DEX_MODE>/' $ORIGINAL_XML > $PATCHED_XML

chown root:root $PATCHED_XML
chmod 0644 $PATCHED_XML
chcon -v u:object_r:system_file:s0 $PATCHED_XML

mount -o bind $PATCHED_XML $ORIGINAL_XML